<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_USA</name>
   <tag></tag>
   <elementGuidId>64e4587f-4308-4ca9-b5a0-83cf973b2973</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#countries > div > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='countries']/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;United States USA&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2303c72d-a0a5-4bd3-9e6c-5a8a4683cb06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.amazon.com/radarbox</value>
      <webElementGuid>78b9c6c6-2128-42f9-94b2-007ba464a73f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>e20685de-c6aa-4735-8db1-10146cfc7d8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>USA</value>
      <webElementGuid>868e897b-7906-40a4-b2aa-3c7b0628ba94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-container&quot;)/table[1]/tbody[1]/tr[2]/td[@id=&quot;countries&quot;]/div[1]/a[1]</value>
      <webElementGuid>9c952fd6-eeee-4066-8648-9a32b7b9b4e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='countries']/div/a</value>
      <webElementGuid>6047995c-9092-4f14-8086-cacafd4d654f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='North America'])[2]/following::a[1]</value>
      <webElementGuid>676a0a4a-4d26-4516-b156-c894a94b273e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy now at'])[1]/following::a[1]</value>
      <webElementGuid>57c64208-7ea9-4074-bff6-7e3215b2e5cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Canada'])[1]/preceding::a[1]</value>
      <webElementGuid>cb846dad-015e-4628-a641-f849dab58f23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.amazon.com/radarbox')]</value>
      <webElementGuid>bae5572d-4fcd-4cbd-932b-801609578d95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/a</value>
      <webElementGuid>e649f88a-627c-4d07-aaa2-681ba85b2430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.amazon.com/radarbox' and (text() = 'USA' or . = 'USA')]</value>
      <webElementGuid>c9218b6b-11a7-4a3c-adfe-c80d6a15fb37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
