<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>eeedd2db-d68d-4798-a8e9-f2edd559bc8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ebay > a > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ebay']/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ebay >> internal:role=link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>94ce8f59-f73b-4d82-bf4c-3ecf22f870bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/img/store/ebay.png</value>
      <webElementGuid>4755aa99-4c0d-4325-ace7-eec8fb6d754f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ebay&quot;)/a[1]/img[1]</value>
      <webElementGuid>81196a3c-8b1a-4a94-b267-dca888b7b192</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ebay']/a/img</value>
      <webElementGuid>f9886cc3-32a9-4730-8ec3-aef46dd1dde1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/img</value>
      <webElementGuid>06eb8e26-9a57-40a5-9294-e4267403cf3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/img/store/ebay.png']</value>
      <webElementGuid>a02ff771-882a-4e9c-a7b2-b157ceaf40fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
