<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path</name>
   <tag></tag>
   <elementGuidId>11be16ec-f233-40a8-9986-bdc6c5647181</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#splash-close-container > svg > path</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#splash-close-container path</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>7cac009c-5a2d-4eae-a76c-a243ae5775d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M 14,1.41 12.59,0 7,5.59 1.41,0 0,1.41 5.59,7 0,12.59 1.41,14 7,8.41 12.59,14 14,12.59 8.41,7 Z</value>
      <webElementGuid>7bbcb487-f05c-496c-9de5-7b5a932d4b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;splash-close-container&quot;)/svg[1]/path[1]</value>
      <webElementGuid>25bad05c-6da0-4c38-ab56-d7c67ca5d498</webElementGuid>
   </webElementProperties>
</WebElementEntity>
